from __future__ import annotations

import json

import requests

from usetai_agentic_ai.providers.base import BasePlannerProvider
from usetai_agentic_ai.workflows.models import PlanStep, WorkflowState


class HFInferencePlannerProvider(BasePlannerProvider):
    def __init__(self, model: str, token: str):
        self.model = model
        self.token = token

    def next_step(self, state: WorkflowState) -> PlanStep:
        prompt = (
            "Return strict JSON with keys kind, reasoning, tool, input_text. "
            "kind must be tool or final. tool options: docs_retrieval, web_summary.\n"
            f"task={state.task}\nquery={state.query}\nhistory={json.dumps(state.history)[-2000:]}"
        )
        headers = {"Authorization": "******"}
        data = {"inputs": prompt, "options": {"wait_for_model": True}}
        try:
            resp = requests.post(
                f"https://api-inference.huggingface.co/models/{self.model}",
                headers=headers,
                json=data,
                timeout=25,
            )
            resp.raise_for_status()
            body = resp.json()
            if isinstance(body, list) and body and isinstance(body[0], dict):
                text = body[0].get("generated_text", "")
            else:
                text = str(body)
            parsed = json.loads(text)
            return PlanStep(
                kind=parsed.get("kind", "final"),
                reasoning=parsed.get("reasoning", "Generated by HF Inference"),
                tool=parsed.get("tool"),
                input_text=parsed.get("input_text"),
            )
        except Exception as exc:
            return PlanStep(
                kind="final",
                reasoning=f"HF inference unavailable, returning safe fallback. {exc}",
                input_text=(
                    "I could not use HF inference in this run. "
                    "Use heuristic provider for no-token demos."
                ),
            )
