from __future__ import annotations

import json

import requests

from usetai_agentic_ai.providers.base import BasePlannerProvider
from usetai_agentic_ai.workflows.models import PlanStep, WorkflowState


class OllamaPlannerProvider(BasePlannerProvider):
    def __init__(self, base_url: str, model: str):
        self.base_url = base_url.rstrip("/")
        self.model = model

    def next_step(self, state: WorkflowState) -> PlanStep:
        prompt = (
            "Return strict JSON with keys kind, reasoning, tool, input_text. "
            "kind must be tool or final. tool options: docs_retrieval, web_summary.\n"
            f"task={state.task}\nquery={state.query}\nhistory={json.dumps(state.history)[-2000:]}"
        )
        payload = {"model": self.model, "prompt": prompt, "stream": False}
        try:
            resp = requests.post(f"{self.base_url}/api/generate", json=payload, timeout=20)
            resp.raise_for_status()
            text = resp.json().get("response", "")
            data = json.loads(text)
            return PlanStep(
                kind=data.get("kind", "final"),
                reasoning=data.get("reasoning", "Generated by Ollama"),
                tool=data.get("tool"),
                input_text=data.get("input_text"),
            )
        except Exception as exc:
            return PlanStep(
                kind="final",
                reasoning=f"Ollama unavailable, returning safe fallback. {exc}",
                input_text=(
                    "I could not use Ollama in this run. "
                    "Switch provider to heuristic for offline demos."
                ),
            )
